### ISSUE TITLE
Cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by gaosh** [facebookresearch/adversarial_image_defenses#12]
I installed Faiss and other packages followed instruction, but I got these errors when I try to run the demo. My environment is pytorch 0.4 and python 3.6.

Traceback (most recent call last):
  File "adversarial/examples/demo.py", line 17, in <module>
    from adversarial.gen_transformed_images import generate_transformed_images
  File "/home/shangqian/anaconda3/lib/python3.6/site-packages/adversarial/gen_transformed_images.py", line 14, in <module>
    from lib.defenses import get_defense
  File "/home/shangqian/anaconda3/lib/python3.6/site-packages/adversarial/lib/defenses.py", line 20, in <module>
    from lib.transformations.quilting_fast import quilting
  File "/home/shangqian/anaconda3/lib/python3.6/site-packages/adversarial/lib/transformations/quilting_fast.py", line 17, in <module>
    QUILTING_LIB = ctypes.cdll.LoadLibrary(os.path.join(os.path.dirname(__file__), "libquilting.so"))
  File "/home/shangqian/anaconda3/lib/python3.6/ctypes/__init__.py", line 426, in LoadLibrary
    return self._dlltype(name)
  File "/home/shangqian/anaconda3/lib/python3.6/ctypes/__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/shangqian/anaconda3/lib/python3.6/site-packages/adversarial/lib/transformations/libquilting.so: cannot open shared object file: No such file or directory

**Comment by gaosh** [comment]
Ok, thanks for your answer.
